### ISSUE TITLE
User Defined Extensions and code templates deployment through an Update Center ?

### ISSUE THREAD

**Issue by dc55028** [oracle/oracle-db-examples#115]
Hi,

Is it possible to add "User Defined Extensions" or code templates to SQL Developer through a packaged extension bundle ?

Thanks

**Comment by bjeffrie** [comment]
For user defined extensions, yes. Code templates I'll have to research. (Depends how they are persisted.)

The (sqldeveloper/extension/readme.md) [Examples](https://github.com/oracle/oracle-db-examples/tree/master/sqldeveloper/extension) page has links to this information.
Specifically

- The  [Set Up / Tutorial](https://github.com/oracle/oracle-db-examples/blob/master/sqldeveloper/extension/setup.md) is a walk through including creating and using check for update bundles. 
- The (external) [Example UpdateCenter](https://github.com/bjeffrie/sqldev-update-center) is both a github repository showing how, as well as an operating update center.

**Comment by bjeffrie** [comment]
Updating/adding templates may be possible via extension but would require changes in sqldeveloper to allow re-loading the template map.

As currently supplied, the user extension mechanism for code templates is via a system property and can be set in the sqldeveloper/bin/sldeveloper.conf file.

     ## Add/override code template definitions from user file(s)
     ## Directory path syntax i.e., ';' separator for Windows, ':' for *nix/mac
     ## e.g., /goodStuff/templates1.xml:/goodStuff/templates2.xml for *nix/Mac
     AddVMOption raptor.user.codetemplates=c:\goodStuff\templates1.xml;c:\goodStuff\templates2.xml

See ~/.sqldeveloper/CodeTemplate.xml for the predefined ones.

The extension mechanism allows for delivering files anywhere within the sqldeveloper installation directory but I can't see any way to update the conf file.

**Comment by dc55028** [comment]
Thanks for the pointers to the update sites, I'll try that.

>  AddVMOption raptor.user.codetemplates=c:\goodStuff\templates1.xml;c:\goodStuff\templates2.xml

I haven' managed to make that work.
I am using Windows 10 and SQLDev version 20.2, I tried to put the AddVMOption line in the sqldeveloper.conf file of the application directory, in the product.conf file of the user's AppData directory, writing it with slashes both ways, using "AddVMOption -Draptor.user...", but sqldeveloper just doesn't try to load the file I put there.

**Comment by bjeffrie** [comment]
Hmm, let me check that.

**Comment by bjeffrie** [comment]
raptor.user.codeTemplates
my apologies.

**Comment by dc55028** [comment]
That was it.

It works with forward slashes in the path (/) even on Windows.
