### ISSUE TITLE
Error: ORA-00904: "EMPLOYEE_ID": invalid identifier

### ISSUE THREAD

**Issue by brunojmm97** [oracle/oracle-db-examples#118]
Hi.

I'm trying to use this API but I keep on getting this error:  "ORA-00904: "EMPLOYEE_ID": invalid identifier"

I just used the same code so I guess that the problem is in my DB table.

[
![image](https://user-images.githubusercontent.com/49170763/90392894-a6b04c80-e087-11ea-84f6-0b0eedfc3b55.png)
](url)

**Comment by sanjana1604** [comment]
@brunojmm97  change the column_name ID to EMPLOYEE_ID

**Comment by sanjana1604** [comment]
@brunojmm97 I would like to solve this issue.

**Comment by sanjana1604** [comment]
@brunojmm97 try to change the column_name from ID to EMPLOYEE_ID
