### ISSUE TITLE
[Connection Helper] Service name with dot not working

### ISSUE THREAD

**Issue by marcorosi** [oracle/oracle-db-examples#125]
Hello,

glad to read of the Connection Helper from @bjeffrie because it will be VERY useful for my team.

We have some problem using it with because SQL Developer doesn't seem to properly manage the request when the service name contains a dot (maybe it treats it as a SID?)

if i do: 

`java -jar ConnectionHelperClient.jar -Bubba=hr@localhost:1521/orcl`

SQL Developer open a dialog asking for the password  

if I do:
`java -jar ConnectionHelperClient.jar -Bubba=hr@localhost:1521/orcl.oracle.com`   

The CLI prints "Request Submitted" but i don't see any dialog in SQL Developer

This prevents us to use the extension because we have service names with dots, I tried to look at the source code but it seems out of sync.

TIA
M

**Comment by bjeffrie** [comment]
Thanks to @mattiaforc, the changes needed have been made. I'll update the example update center for those who aren't building themselves.
