### ISSUE TITLE
DependencyViewerExample - Editor not shown for PL/SQL nodes

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oracle/oracle-db-examples#16]
Hi @bjeffrie,

Thanks for the nice [DependencyViewerExample](https://github.com/oracle/oracle-db-examples/blob/master/sqldeveloper/extension/xml/individual/DependencyViewerExample.xml). I like the SQL Developer links. I was looking for an example to add an editor for a PL/SQL node and this example looked promising.

However, it works for table and view nodes but not for PL/SQL nodes such as functions, procedures and packages. I tried to change some configuration but could not figure out the right values to make it work for PL/SQL nodes.

### Working
The "tab" for "Dependency Edges Query" is available for this view
![plscope_1](https://user-images.githubusercontent.com/3883171/27757066-908e8a26-5dfd-11e7-87b7-bcae7717887a.png)

### Not working
"tab" "Dependency Edges Query" is missing for the package body:
![plscope_2](https://user-images.githubusercontent.com/3883171/27757070-95a30bfe-5dfd-11e7-8b8a-7482f5df7cb9.png)

Any help is very much appreciated.

Thank you.
Philipp

**Comment by bjeffrie** [comment]
Hi Phiipp, thanks for trying the examples. I'll take a look & get back to you. PlSqlNodes are handled a bit differently than others internally  so need to review my notes in the code and do a bit of research. -Brian.

**Comment by bjeffrie** [comment]
Hi Philipp,

It's a bit clumsy, but for package,procedure,function the add-on viewers are shown in a popup describe dialog. To use it, place the cursor on the name in the create or replace clause and use the context menu (or default short-cut shift+F4) to open it. Note that it doesn't seem to recognize quoted names so hopefully this will not be an issue for your use case.
![popupdescribe-menu](https://user-images.githubusercontent.com/24436934/27835323-8bbe1f68-60a8-11e7-9d07-1d398699b597.png)
![popupdescribe-viewer](https://user-images.githubusercontent.com/24436934/27835329-93ea5a62-60a8-11e7-9645-c35a6aca622b.png)

*(I modified the example query by commenting out --AND (OWNER != declOwner OR OBJECT_NAME != declObject) so it would show something)*

FYI this popup describe feature works for any name in the code that the parser recognizes as an object, such as table names.
![image](https://user-images.githubusercontent.com/24436934/27835531-55ae09be-60a9-11e7-9288-0e102d621630.png)

**Comment by PhilippSalvisberg** [comment]
Hi Brian,

"Popup Describe" 😲 Wow.  I would never have figured it out, without your help. Thank you. 

> FYI this popup describe feature works for any name in the code that the parser recognizes as an object, such as table names.

Yes, this makes it very useful. It resolves synonyms too. 

My code works as well (I just wasn't just aware of it). - I have configured a shortcut for "Popup Describe" on my SQL Developer installation (macOS) to simplify the usage. 

However, it might still be helpful to extend the "tabs" within a PL/SQL editor. Nonetheless I'm happy now to have a solution.

Thanks,
Philipp

**Comment by bjeffrie** [comment]
Can't promise anything, but I put it 'on the list' for SQL Developer improvements. -Brian.
SQLDEV-475: Allow extension editors/viewers to show as tabs for PlSqlNodes
