### ISSUE TITLE
https://jsao.io/ is down?

### ISSUE THREAD

**Issue by ldsouza93** [oracle/oracle-db-examples#172]
please tell me it'll be back

**Comment by cjbj** [comment]
I understood from @dmcghan that the domain has not been renewed.
You can find most content on places like Oracle Magazine or DZone.  e.g.
  https://blogs.oracle.com/oraclemagazine/build-rest-apis-for-nodejs-part-1
  https://github.com/oracle/oracle-db-examples/tree/master/javascript/rest-api

**Comment by ldsouza93** [comment]
thanks for the reply, the sad thing is that the part 5 of the tutorial is gone, is it still up somewhere?
that tutorial really help me a lot

**Comment by cjbj** [comment]
I don't believe it was ever written?  I know the series wasn't able to be completed.
