### ISSUE TITLE
SQL Developer XML application extension

### ISSUE THREAD

**Issue by mvrba** [oracle/oracle-db-examples#20]
I should like create special XML extension for  organization of DB objects for defined application.
See to screenshot : 
![applicationexample](https://user-images.githubusercontent.com/31552689/29988801-67c5d90c-8f6f-11e7-95d9-f3875b06636f.png)

On each DB object, user can open context menu.  See following screenshot for PACKAGE. 
![menu](https://user-images.githubusercontent.com/31552689/29988800-67be98ea-8f6f-11e7-85e3-afa5ab67f828.png)

But when I click to Edit menu item the editor is opened but without the code.
The same behavior I have on triggers, functions and procedure.   

Do you have some idea how I can solved this problem ?

Folders are created as a special type and rows under the folder are generated by following SQL stmt.
Part XML extension definition is following:

`<objectType connType="Oracle" id="APP_PACKAGES" requiresParent="true">
   <folder>
	   <icon  RSKEY="PACKAGE_FOLDER_ICON"/>
	   <label RSKEY="PACKAGE_LABEL"/>
	   <queries>
		  <query>
			  <sql>
				  <![CDATA[
								 SELECT  ao.OBJECT_NAME,  ao.OBJECT_NAME TABLE_OBJECT_NAME, 'PACKAGE' type
								 from APP_OBJECT ao, app_schema_mapping asm, all_objects alt
								 where ao.APP_NAME=:APP_NAME
									 and asm.app_name=ao.app_name
									 and asm.target_schema=ao.owner                                                                                                                   
									 and  ao.OBJECT_TYPE='PACKAGE'
									 and          alt.object_name=ao.object_name
									 and alt.owner = asm.source_schema
									 and alt.object_type=ao.object_type
				  ]]>
			  </sql>
			  <columns>
				  <column filterable="true" sortable="true" id="NAME">
					 <colName>
						 <![CDATA[OBJECT_NAME]]>
					 </colName>
				  </column>
			  </columns>
		  </query>
	   </queries>                                            
   </folder>
   <node nodeClass="oracle.dbtools.raptor.navigator.plsql.PlSqlNode" />
</objectType>`

Thanks for help.

**Comment by bjeffrie** [comment]
Sorry for the delay, I was on vacation.
The connType and id attributes in the objectType element is what the viewers key off of.
In your example, the id should be "PACKAGE"

**Comment by gvenzl** [comment]
@bjeffrie, can we close this issue or is there still something outstanding?

**Comment by bjeffrie** [comment]
Not sure how I lost this but yes I'll close it.
