### ISSUE TITLE
Are there some samples about Oracle Spatial with JDBC and other languages?

### ISSUE THREAD

**Issue by zxj5470** [oracle/oracle-db-examples#22]
Nice samples!

However I use occi to select sth from GEOMETRY is further faster than JDBC.
I think I got a wrong way.
c++: in 500ms

and the GEOMETRY type was parsed into oracle.sql.STRUCT and needs cast into JGeometry ...(it takes me too much time ...) 
Java: more than 4000ms

I wish there be some samples about Oracle Spatial.
Thanks:pray:

**Comment by bjeffrie** [comment]
I don't know anything about geometry/spatial but I'll ask around. Brian.

**Comment by agodfrind** [comment]
Can we see some code so that we can try and reproduce that? Both timings are way too high ...

**Comment by gvenzl** [comment]
@zxj5470, can you provide the piece of code to reproduce this, please?

**Comment by gvenzl** [comment]
Closing this due to lack of response. @zxj5470, please reopen when you have a code sample that you can share with us.
