### ISSUE TITLE
Changes in SODA.md

### ISSUE THREAD

**Issue by Fxztam** [oracle/oracle-db-examples#27]
Please change the installing sequence (jar dependency) and 
actualize version no. to orajsoda-1.0.5.jar in SODA.md ::

(ii) Load the latest javax.json-1.0.4.jar
        loadjava -r -v -u hr/hr javax.json-1.0.4.jar
		
(iii) Upload orasoda.jar in your database schema
        loadjava -r -v -u hr/hr orajsoda-1.0.5.jar

Works great 👍

**Comment by 912d** [comment]
I made pull request according to this issue.
Related: https://github.com/oracle/oracle-db-examples/pull/35

**Comment by Kuassim** [comment]
I've fixed this a whole back.
