### ISSUE TITLE
oracle 12c - ORA-22275, with JDBC 12.1.0.1

### ISSUE THREAD

**Issue by feng2** [oracle/oracle-db-examples#28]
https://community.oracle.com/message/14331188#14331188
From oracle10 version, the function "setStringForClob" has been added in the JDBC for CLOB type.
     oracle.jdbc.OraclePreparedStatement.setStringForClob(int i, String s)
this show: oracle support the CLOB type is String in the code
but i use this to batch update the clob type's data, but ORA-22275 error occur

**Comment by gvenzl** [comment]
Closing this as the question in the forum has been marked as answered and is not related to this GitHub repo.
