### ISSUE TITLE
Run Script Button Accessible from Extension?

### ISSUE THREAD

**Issue by mwilliams596** [oracle/oracle-db-examples#44]
Is it possible to access the Run Script button in a Worksheet from an extension?

This is being considered to be able to disable/enable the button during extension processing.

Please advise if additional details are needed. Keeping it short and simple to start.

**Comment by bjeffrie** [comment]
Hmm, it may just be the mail integration being slow, but just in case,

Like most things, "It depends". In general the answer is no. The actions are local to the individual worksheet. The worksheet busy internal state that controls if the run buttons are enabled is private. There is a slim chance depending on exactly how your extension recognizes / wraps the SQL execution for tracing.

**Comment by mwilliams596** [comment]
I suspected that there would be internal considerations but wanted to toss this question out there all the same. I appreciate the reply. We'll have a think about things and see where it leads.

**Comment by mwilliams596** [comment]
Closing this question. I think we have enough information based on latest internal discussion here. Thanks!

**Comment by bjeffrie** [comment]
Any time.
