### ISSUE TITLE
Kill SQL Developer

### ISSUE THREAD

**Issue by Gibson85** [oracle/oracle-db-examples#60]
Every time I have end of work this fu..... tool takes minutes to close (if at all) and has cost me a lot of life time. Please deliver your excellent software in the future with this batch script. Thanks.

```
taskkill /f /im "sqldeveloper64W.exe"
```

**Comment by Gibson85** [comment]
Sorry for my late respond. Latest version 19.2.1.247.2212 closes instantly now :).

**Comment by Gibson85** [comment]
Sorry to say the problem still exists. After a while the SqlDeveloper can't be closed anymore. In addition after some time it always loses the databse connections what is totally annoying. Then you have to accept 3-4 dialog boxes telling you about that. And the overall performance is horrible. One wrong click e.g. to the model tab and your sqldeveloper blocks for 20 seconds. Have you ever worked productive with this tool?

**Comment by gvenzl** [comment]
Hey @krisrice, can you follow up on this once more, please?

**Comment by gvenzl** [comment]
Closing due to lack of response. Please reopen if this is still and issue.
