### ISSUE TITLE
SQL Developer Extension Create

### ISSUE THREAD

**Issue by umitsamli** [oracle/oracle-db-examples#81]
Hi,
I am trying to develop an extension on SQL developer.
Extension content will try to connect to the TEST database automatically with 30 users. Once connected, I will run certain scripts. But I could not connect to TEST database by changing user. I need to use the connection on SQLDeveloper. Each computer will have different users and connections.
I'm putting the sample code block below.
How do I make changes to fixed connections here?

`
package connectioncontrol;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.List;

import oracle.dbtools.raptor.utils.Connections;

import oracle.ide.log.LogManager;

import oracle.javatools.db.DBException;

public class test {
    List<String> usernameList;

    private static final void LogMessage(String level, String msg) {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        LogManager.getLogManager()
                  .getMsgPage()
                  .log("CC: [" + dateFormat.format(new Date()) + "] " + level + ": " + msg + "\n");
    }

    public void run() {
        Connections conns = Connections.getInstance();
        try {
            String[] l = conns.getConnNames();
            for (String connectionName : l) {
                String displayConnectionName = connectionName;
                if (displayConnectionName.contains("%23")) {
                    displayConnectionName = connectionName.substring(connectionName.indexOf("%23") + 3);
                }
                for (String username : usernameList) {
                    //conns  change user and password
                    //
                    //
                    Statement sqlStatement = null;
                    try {
                        sqlStatement = Connections.getInstance()
                                                  .getConnection(connectionName)
                                                  .createStatement();
                        String QueryString = "SELECT 1 FROM DUAL";
                        ResultSet rs = sqlStatement.executeQuery(QueryString);
                        while (rs.next()) {
                            LogMessage("DEBUG", "query returned: " + rs.getString("SYSDATE"));
                        }
                    } catch (SQLException e) {
                        LogMessage("ERROR", displayConnectionName + " " + e.toString());

                    } catch (DBException e) {
                        LogMessage("ERROR", displayConnectionName + " " + e.toString());

                    } finally {
                        if (sqlStatement != null) {
                            try {
                                sqlStatement.close();
                            } catch (SQLException e) {
                                LogMessage("ERROR", displayConnectionName + " " + e.toString());
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            LogMessage("ERROR", "GLOBAL:  " + e.toString());
        }
    }

}

`

**Comment by bjeffrie** [comment]
So you want to use multiple user/pw with one SQLDev Connection? Do I understand correctly or would multiple (java.sql) connections via the same credentials work?

What problem is the extension meant to solve? Throwing script(s) at a bunch of connections would seem more a scripting thing you could do with sqlcl to me but I don't know your context.

Note that SQLDev Connections are identified by {store name}%{connection name} and define a  {user}+[{password}+]{connection driver info e.g. host,port,sid/service[,role], etc. for Oracle DB} 

That said, there are utility functions for getting unique (java.sql) connections for a given SQLDeveloper connection and also for creating a SQLDev Connection for a new user/pw based on an existing one. E.g.,

  for (String qualifiedConnectionName : ConnectionResolver.getConnectionNames()) {
    // Get shared connection for qualified name (this is the one SQLDeveloper uses for the navigator and displays)
    java.sql.Connection sharedConn = ConnectionResolver.getConnection(qualifiedConnectionName);
    
    // Get unique (unnamed) connection using credentials from qualifiedConnectionName 
    java.sql.Connection uniqueConn = ConnectionResolver.getUniqueConnection(qualifiedConnectionName);
    
    // Get new connection for name/pw using connection driver info from qualifiedConnectionName
    String folderName = null; // Will use "Connections based on " + qualifiedConnectionName if null
    String username = "someUser"; // Must be unique as it will be used as the connection name
String password = "somePassword";
    ConnectionUtils.addNewConnectionBasedOn(folderName, qualifiedConnectionName, username, password);
    String newConnQualifiedName = ConnectionResolver.getQualifiedConnectionName(username);
    java.sql.Connection newConn = ConnectionResolver.getConnection(newConnQualifiedName);
    
    java.sql.Connection myConn = newConn; // or uniqueConn
    String displayName = ConnectionResolver.getConnectionName(myConn); // 
    // See if one of the DBUtil.execute(...) methods work for you - it handles locking/error reporting
    // do stuff ...
   
   // if using newConn, close and remove sqldev connection  
    Connections.close(newConnQualifiedName);
// (*%_%_$ I'm going to have to add some way for extensions to programmatically delete the connection to sqldev itself. (19.4 hopefully)

**Comment by bjeffrie** [comment]
Added utility functions for 19.4. Example usage creating, openening, and setting up to close(if needed)+delete the new connection when sqldeveloper exits: 

Given a (fully qualified) connectionName for an existing connection
```
                SwingUtilities.invokeLater(() -> {
                    final String folder = "Testing";
                    final String user = "someUser"; // Must be unique as it will be used as the connection name
                    final String pw = "somePassword";
                    ConnectionUtils.addNewConnectionBasedOn(folder, connectionName, user, pw);
                    final String fqName = ConnectionUtils.getFqConnectionName(user);
                    ConnectionUtils.connect(fqName);
                    ExitCommand.addShutdownHook(new ShutdownHook() {
                        @Override
                        public boolean canShutdown() {
                            return true;
                        }
                        @Override
                        public void shutdown() {
                            ConnectionUtils.closeAndDeleteConnection(fqName);
                        }
                    });
                });
```

**Comment by bjeffrie** [comment]
No response to the answer in a month. Assuming it is OK or user no longer cares. Closing.
